### ISSUE TITLE
(Question) Why XeTeX?

### ISSUE THREAD

**Issue by copycat-killer** [tectonic-typesetting/tectonic#41] opened 2017-05-31 17:10 UTC
Could you please explain the choice of XeTeX over LuaTeX?

It surprises me a bit, since it seems that the latter has been chosen as pdfTeX successor, but also has full Lua power.

Mh, maybe are you planning to add Rust power to Tectonic? 😃

**Comment by jtojnar** [comment] 2017-05-31 21:45
See also https://www.reddit.com/r/rust/comments/6e2x6m/tectonic_a_complete_modernized_selfcontained/di83x77/

**Comment by pkgw** [comment] 2017-06-01 14:22
Yes, I'll reproduce the Reddit comment here:

In my initial investigations it seemed that XeTeX had better Unicode and font support, although I'm not a LuaTeX user so I don't know how correct that is. And to be honest: I'm already asking users to deal with one obscure computer language; I don't want them to have to deal with two.

As a downside, it looks like LuaTeX has a largely C implementation that has already done much of the cleaning and modernization work that I need to do within Tectonic. Would have been nice to have leveraged that.

Various people have asked about the choice so perhaps it should go into the documentation at some point ... although things have gotten far enough such that at this point, it is what it is.

I'm going to close this as an issue.

**Closed by pkgw** 2017-06-01 14:22 UTC
