### ISSUE TITLE
Doesn't work when CWD is different than input path

### ISSUE THREAD

**Issue by skrat** [tectonic-typesetting/tectonic#52] opened 2017-06-01 11:23 UTC
```
$ tectonic Documents/xxx.tex
...
Running xdvipdfmx ...
error: cannot open "Documents/xxx.xdv
```

**Comment by pkgw** [comment] 2017-06-01 14:00
I am doing to close this as a duplicate of #31.

**Closed by pkgw** 2017-06-01 14:00 UTC
