### ISSUE TITLE
Biber error: "cannot find _____.bib"

### ISSUE THREAD

**Issue by aterenin** [tectonic-typesetting/tectonic#796] opened 2021-06-21 15:26 UTC
Posting a standalone issue following Biber support added in #35. The following works if `backend=bibtex` option is used but not if it is removed.

MWE.tex
```tex
\documentclass[12pt]{book}

\usepackage{biblatex}
\bibliography{citations}

\begin{document}

\title{MWE}

\maketitle

\textcite{example}

\printbibliography

\end{document}
```

citations.bib
```
@inproceedings{example,
	author = {Example Example},
	booktitle = {Example Example},
	title = {Éxample Example},
	year = {2021}}
```

Output
```
aterenin@MacBook-Pro MWE % tectonic mwe.tex
Running TeX ...
Running external tool biber ...
error: the external tool exited with an error code; its stdout was:

===============================================================================
INFO - This is Biber 2.16
INFO - Logfile is 'mwe.blg'
INFO - Reading 'mwe.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'citations.bib' for section 0
ERROR - Cannot find 'citations.bib'!
INFO - ERRORS: 1
===============================================================================
error: its stderr was:

===============================================================================
===============================================================================
error: the external tool exited with error code 2

```

**Comment by pkgw** [comment] 2021-06-21 15:57
Thanks for reporting! I'll have to do a bit of digging to identify the "right" approach but I anticipate that this should be straightforward to fix.

**Comment by WtfJoke** [comment] 2021-06-21 18:47
Same problem with this sample repo
https://github.com/WtfJoke/setup-tectonic-sample

**Comment by zzamboni** [comment] 2021-06-22 11:25
I'm seeing the same error with a document in which I use `\addbibresource`, even when specifying the `backend=biber` option to `biblatex`. My minimum example would be very similar to the repo posted by @WtfJoke.

BTW: I think it's AWESOME that Tectonic now supports biber!

**Comment by Siborgium** [comment] 2021-06-29 04:01
@zzamboni it seems to work with absolute paths.

**Comment by zzamboni** [comment] 2021-06-29 11:51
@Siborgium thanks for the tip! I can confirm that using the absolute path of the `.bib` file in `\addbibresource` works.

This is not ideal since I would like the filenames to be relative to the current file and not dependent on where the directory is checked out, but it's good to have a workaround until this bug get fixed :)

**Comment by pkgw** [comment] 2021-07-01 13:41
@zzamboni The goal will definitely be to make it so that absolute paths aren't required, and I'm confident that I can fix up the support to do so pretty easily. The code that launches the tool just needs to be extended to add the "right" files to the temporary work directory, for some definition of "right".

**Comment by pkgw** [comment] 2021-07-03 19:14
OK, #804 ought to address this. My testing has been pretty light, though, so if anyone wants to give it a spin, that wouldn't hurt. I never knew what the `.run.xml` file was for, but it comes in very handy here!

**Comment by pkgw** [comment] 2021-07-04 17:53
I've just released version 0.7.1 which should hopefully do a lot better on this topic. I'm going to close this issue — please file new ones if there are further issues. I'm *pretty* sure that the new approach should be pretty robust, although inputs containing absolute paths to `.bib` files will now fail to build, I think.

**Closed by pkgw** 2021-07-04 17:53 UTC

**Comment by zzamboni** [comment] 2021-07-04 20:18
@pkgw I can confirm it works now without having to specify absolute paths. Thanks!

(BTW it still works with absolute paths as well)

**Comment by aterenin** [comment] 2021-07-04 20:33
Works for me as well! Big thanks for this! 🎉🎉🎉
