### ISSUE TITLE
tectonic -X new harmful 

### ISSUE THREAD

**Issue by dougransom** [tectonic-typesetting/tectonic#846] opened 2021-12-02 22:04 UTC
Tectonic creates projects that won't compile with other tex programs.  This is going to drive users mad over the long run, there is no benefit, it can only create problems for us down the road.  

These three files are implicitly concatenated together by tectonic.  
`src/_preamble.tex
src/index.tex
src/_postamble.tex`

If there is some advantage to a workspace, why not just have index.tex import the other two files through some latex command?

I suggest  this behavior be changed immediately, to avoid users creating these projects with the implicit concentation, and providing an error message requiring a fix in index.tex when compiling existing projects.

**Comment by pkgw** [comment] 2021-12-03 14:44
OK — I'm going to attempt to convince you that this design choice is in fact the correct one.

Big picture: In a certain sense, the whole reason that the Tectonic project exists is to break compatibility with existing TeX engines. I believe that there are enormous usability/UX wins that can be unlocked if we allow ourselves to break certain things, and symmetrically that you *have* to break certain things in order to solve certain big problems. So, while I don't want to be gratuitously incompatible with the ecosystem, interchangeability with other TeX engines is an explicit *non*-goal — it's just too constraining. That's why I'm not just working to improve XeTeX.

Given that context, there's certainly some tension on the compatibility question. It's exactly the concern that you voiced: it's going to be unpleasant if people create documents using Tectonic with the expectation that they can be compiled with other engines, only to discover that they've used some functionality unique to Tectonic that prevents this. I want people to "opt in" to creating Tectonic-specific documents that can take advantage of unique features, but may not be compilable with other engines.

That's exactly what `tectonic -X new` is. While you could imagine a similar approach that instead prioritizes compatibility, the contract for this command (implicit only, I'll admit) is the new document is only going to be portable to other engines "at your own risk". Precisely because the `Tectonic.toml` "document model" approach is unique to Tectonic and so different than traditional TeX tools, I hope that it signals to people that their documents won't necessarily just drop into another engine successfully. The issue you're raising here suggests that it might be good to make this more explicit.

One day, it might be nice to have a `compatible` flag in `Tectonic.toml` that users could set to explicitly indicate that they want their documents to be compatible with other engines, causing errors to be raised if they use features unique to Tectonic. This would be associated with a requirement that the preamble and postamble files be empty. On the other hand, so much of "compatibility" is an emergent property coming from the hundreds of LaTeX class and style files that might underlie the document compilation, so that it's really hard to say with confidence whether a given document will compile as intended on another platform.

I hope this helps clarify the motivation for the current design.

**Comment by dougransom** [comment] 2021-12-04 18:33
Ok, i am probably wrong :).

**Comment by PHPirates** [comment] 2021-12-04 19:41
> The issue you're raising here suggests that it might be good to make this more explicit.

Yes, I think this deserves a sentence on the homepage, that compatibility with other LaTeX engines is not a goal of Tectonic, because from what I've seen so far many new users are frustrated when they try to switch to Tectonic (and from Tectonic to something else, though that's probably less common) and it doesn't just work out of the box.

**Comment by pkgw** [comment] 2021-12-06 14:22
@PHPirates Yes, that needs some work, along with several other aspects of the intro — for instance, *many* people think that Tectonic wraps around and requires XeTeX/TeXLive. I always postpone working on this stuff since I want to really revamp the entire way that Tectonic is documented (including, er, writing huge quantities of new docs), but that shouldn't get in the way of quality-of-life improvements. Pull requests are always welcome.

I'm going to close this issue. Thanks for reaching out, @dougransom — there are probably a lot of other people with the same reaction as you and hopefully the discussion here will be a helpful resource going forward.

**Closed by pkgw** 2021-12-06 14:22 UTC

**Comment by zzamboni** [comment] 2023-04-24 22:03
@dougransom FWIW, the preamble and postamble can be disabled by setting them to `''` in `Tectonic.toml`, like this:

```
[[output]]
preamble = ''
postamble = ''
```

I am using this to render a single, fully-contained LaTeX file while preserving the Tectonic v2 directory structure.

**Comment by kmccurley** [comment] 2025-04-01 20:57
This is the reason why I uninstalled tectonic five minutes after installing. I don't need another engine that won't compile existing LaTeX files.
