### ISSUE TITLE
tectonic compilation fails if IEEEPARstart command is present

### ISSUE THREAD

**Issue by vinay0410** [tectonic-typesetting/tectonic#506] opened 2019-11-29 13:32 UTC
Culprit Statement in `.tex` file
```
\IEEEPARstart{T}{here} is an ...
```

Error Log:
```
(se-ascii-print.def)
! Font \@IEEEPARstartsubfont=lmroman10-regular]:mapping=tex-text;^^@I^^@I at 19
.97008pt not loadable: Metric (TFM) file or installed font not found.
\IEEEPARstart ...ME \space at \@IEEEtrantmpdimenA 
                                                  \relax \@IEEEtrantmpcountA...
l.42 \IEEEPARstart{T}{here}
                            is an increasing application areas for deep lear...
```

Tectonic Version: `0.1.11`

**Comment by pkgw** [comment] 2019-12-02 15:30
Thanks for the bug report!

I think that two packages must be interacting badly here, since I can't reproduce the problem with an extremely minimal test case:

```tex
\documentclass{IEEEtran}
\begin{document}
\IEEEPARstart{T}{here} is a drop-cap.
\end{document}
```

Does the above document compile for you? Would you be able to post a minimal example that reproduces the failure? Thanks.

**Comment by vinay0410** [comment] 2019-12-03 03:43
HI @pkgw ,
I used the above tex file with a `IEEEtran.cls` and without `IEEEtran.cls` in the same directory.
In the second case tectonic downloaded `IEEEtran.cls`.
In both the cases I got the following error.
```
-- Lines per column: 58 (exact).
! Font \@IEEEPARstartsubfont=lmroman10-regular]:mapping=tex-text;^^@I^^@I at 19
.97008pt not loadable: Metric (TFM) file or installed font not found.
\IEEEPARstart ...ME \space at \@IEEEtrantmpdimenA 
                                                  \relax \@IEEEtrantmpcountA...
l.3 \IEEEPARstart{T}{here}
                           is a drop-cap.
```

Therefore, I can reproduce a failure on Tectonic v0.1.11, both on Ubuntu (installed using cargo) and on MacOS (installed using brew).

**Comment by pkgw** [comment] 2019-12-05 13:56
Very good point — I've been testing with the development version. If I install the latest release, I reproduce your error.

We're overdue for a release, so hopefully 0.1.12 will be out soon. In the meantime, if you're able to install the development version, that should fix your problem. I'll close this issue, but feel free to add more comments or reopen as you see fit.

**Closed by pkgw** 2019-12-05 13:56 UTC
