### ISSUE TITLE
Improve installation story: pre-built packages, easy builds

### ISSUE THREAD

**Issue by alexreg** [tectonic-typesetting/tectonic#4] opened 2017-03-06 18:27 UTC
Please add to this list if you are interested in a package for an OS not listed here.

- [x] Mac OS X (Homebrew) [assigned: @alexreg, @iKevinY]

**Comment by pkgw** [comment] 2017-05-29 19:39
I am not sure how best to do this, but I would love to poll users to get a sense of which kinds of packages would be most useful. For now, any users out there are invited to please add a comment to this bug with the pre-built package that you would most like to see!

**Comment by elahn** [comment] 2017-05-29 22:39
Windows x64

**Comment by sebasmagri** [comment] 2017-05-30 00:02
I just did `cargo install tectonic` and it worked. It should be documented.

**Comment by pkgw** [comment] 2017-05-30 12:59
@sebasmagri Good point! Pull requests to [the website repo](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io) are more than welcome if you've got the inclination 😄. I hope to revamp the install page soon, if I can get a better sense of which install methods would be good for people. I don't want to overwhelm them with too many choices (or overwhelm myself with obligations to make a million different kinds of packages), but the `cargo` option should definitely be there.

**Comment by alexreg** [comment] 2017-05-30 14:24
> but the cargo option should definitely be there.

Yes, perhaps, although I think it should assume all prerequisites are already installed, and the environment is configured. For anything more complicated, you should be instructed to use your package manager.

**Comment by zbeekman** [comment] 2017-05-30 14:41
> I just did cargo install tectonic and it worked. It should be documented.

FYI, with most dependencies installed through Homebrew `cargo install tectonic` failed for me due to problems finding icu-uc.pc.... After setting my PKG_CONFIG_PATH so that it was able to find that file, the compilation fails with GCC-6 and with the default apple/clang compiler....

**Comment by steveklabnik** [comment] 2017-05-30 15:22
You may find https://github.com/japaric/trust useful

**Comment by g2p** [comment] 2017-05-31 02:23
My preferred installation method would be an apt invocation followed by a cargo invocation (or a tar extraction, if you choose to build binaries). The effort in distributing anaconda packages is laudable, but I prefer working with distribution packages and rust crates. I suggested flatpak before, as that's more standard than anaconda, but since the build isn't esoteric and works with cargo that may not be necessary.

**Comment by alexreg** [comment] 2017-05-31 02:45
Since the consumers of this package may be both developers and end-users, I think it's important to be able to avoid `cargo install` completely, in honesty.

**Comment by rekka** [comment] 2017-05-31 04:34
On Ubuntu 17.04, all I needed was

```
sudo apt-get install libfontconfig1-dev libharfbuzz-dev zlib1g-dev
cargo build     # cargo install, etc.
```

This installs all the libraries listed in #15. This would be useful to mention in the installation instructions for Ubuntu.

**Comment by jRimbault** [comment] 2017-05-31 06:34
FYI, there is a package on the [AUR][0]
Is it in anyway related to you ?

[0]: https://aur.archlinux.org/packages/tectonic/

**Comment by pkgw** [comment] 2017-05-31 12:20
@jRimbault I had nothing to do with that. Cool! Although the package description is wrong ...

**Comment by pkgw** [comment] 2017-05-31 12:20
@jRimbault I had nothing to do with that. Cool! Although the package description is wrong ...

**Comment by Nefari0uss** [comment] 2017-05-31 15:31
@jRimbault Glad to see an AUR package. :)

@rekka Is there any reason why it might not work on Bash on Windows?

**Comment by redtrumpet** [comment] 2017-05-31 17:53
@sebasmagri Doing `cargo install tectonic` did not work for me. [Here](https://gist.github.com/redtrumpet/65c08383ac1684baf64fcc5605097f91) is the error. I'm probably missing some packages?

**Comment by jtojnar** [comment] 2017-05-31 21:27
I created PKGBUILD for Arch: https://aur.archlinux.org/packages/tectonic/

**Comment by alexander-bauer** [comment] 2017-05-31 23:20
@jtojnar I see you authored the AUR package -- would it make sense for the PKGBUILD to live in this repository? That would open it up to pull requests and contributions.

**Comment by andrewgho** [comment] 2017-05-31 23:52
As someone who uses LaTeX but doesn't use either of Rust or Anaconda Python, I think the current installation method is a definite obstacle to end user adoption. The long term solution users expect would be proper vendor packages. I think `apt-get install`, `yum install`, `brew install`, and a Windows installer would get you most users, and `cargo install` from source (dependencies are documented but your own problem to install separately) seems like a perfectly reasonable way to accommodate the longer tail.

As a user of symlink based package managers, and as someone who is sometimes on a system where I don't control `/usr/local` or `/usr` directly, I'll also make a plea to make sure any installed package is relocatable (can be installed and symlinked, or installed into a home directory).

**Comment by jtojnar** [comment] 2017-06-01 00:29
@alexander-bauer I do not have an opinion about this, @pkgw is a better person to ask. Though it would open the possibility to automate the push to AUR using Travis deploy hook.

**Comment by rekka** [comment] 2017-06-01 00:50
@Nefari0uss Does bash on Win (like Cygwin) have `apt-get`? I unfortunately do not have any experience with Rust on Windows. But see discussion #32 for a way to install Tectonic on Windows.

**Comment by pkgw** [comment] 2017-06-01 02:54
@jtojnar @alexander-bauer I'm not familiar with Arch Linux infrastructure ... sounds like you're talking about packaging instructions? I was thinking of creating another repo in this organization, `tectonic-packaging` or something, that contained all of those bits and pieces. Would that make sense?

**Comment by alexander-bauer** [comment] 2017-06-01 03:01
@pkgw In Arch, packages are defined by a single shell script called PKGBUILD, and then built in a standard way from there into a tarball. There aren't any hard-and-fast rules about where they need to live, because oftentimes they aren't written by the original code maintainers ([the Arch User Repository package for tectonic, for example](https://aur.archlinux.org/packages/tectonic/)).

When they are associated with the original project, though, it's fairly common practice for them (and files for other distributions' packages) to live in `dist/`. This way, they stay versioned with the primary codebase, and can benefit from any CI solutions the main codebase takes.

If that makes sense to you, I'll open a pull request (with @jtojnar as author on the commit) to create `dist/arch/PKGBUILD`.

**Comment by msehnout** [comment] 2017-06-01 07:44
I'd prefer native packages for Linux distributions. Copr repositories can be used for Fedora/CentOS RPM packages:
https://copr.fedorainfracloud.org/

**Comment by chris-morgan** [comment] 2017-06-01 07:55
WSL is a complete Linux environment (Ubuntu by default), without using the actual Linux kernel. With a few exceptions for things that haven’t been implemented yet and things that directly integrate with the kernel (e.g. drivers), anything that runs on a Linux distribution will run on WSL with no changes. Instructions that work for Ubuntu cover WSL.

**Comment by viatcheslavmogilevsky** [comment] 2017-06-01 13:29
Any thoughts about docker image?

**Comment by alexreg** [comment] 2017-06-01 14:41
FYI, OS X Homebrew formulas (packages) go in a "tap" repository, so they can't really be maintained within this repository.

**Comment by alexander-bauer** [comment] 2017-06-01 15:01
@alexreg I don't actually know much of anything about Homebrew, but [this page](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#creating-a-tap) says it can also be just a directory, and presumably one within a Git repository, so it might be able to live in `dist/homebrew/`

**Comment by pkgw** [comment] 2017-06-01 17:32
OK! I have update [the install instructions](https://tectonic-typesetting.github.io/en-US/install.html) on the website. They now mention the AUR package and `cargo install`, and Windows, with more details for more platforms.

Because the website has its own GitHub repo and its own issue tracker, **please reroute discussions about how the installation options are presented on the website** to [the website's issue tracker](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/issues).

**Discussions relating to the technical infrastructure needed to provide more, better installation instructions** remain appropriate for this thread.

**Comment by alexreg** [comment] 2017-06-01 17:44
@alexander-bauer That has the limitation that it can't be part of the official package set, and even if you run a separate tap, it has to be a repository of its own, with everything in the root directory, I believe.

**Comment by iKevinY** [comment] 2017-06-02 19:08
Since all of Tectonic's dependencies can be installed on macOS through Homebrew, it should be fairly straightforward to write a formula for it. I wrote the [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/exa.rb) for [`exa`](https://github.com/ogham/exa) (another Rust program), and would be happy to help out writing one for Tectonic as well!

**Comment by pkgw** [comment] 2017-06-02 19:19
@iKevinY It would be awesome if you could prepare one! Is there a potential for problems because `harfbuzz` has to be built with the `--enable-graphite2` option, which is not enabled by default?

Anyway, if you add a formula, please file an issue on [the website tracker](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/issues) as a ping for it to be documented on the installation page.

**Comment by iKevinY** [comment] 2017-06-02 20:46
I imagine that there's way to specify that a dependency requires a certain option, but at the moment I'm not certain about that. I'll try things out over the weekend and see if I can get a working formula!

**Comment by monsanto** [comment] 2017-06-03 08:03
Need to install `libgraphite2-dev` as well on Ubuntu 16.04 LTS for this to build via `cargo`

**Comment by pkgw** [comment] 2017-06-03 12:25
@monsanto Thanks; fixed.

**Comment by iKevinY** [comment] 2017-06-03 20:56
Quick update on the Homebrew formula: it's definitely possible to specify that the `harfbuzz` dependency requires `graphite2`, so that shouldn't be a problem. I've also figured out the environment variables that need to be set during the installation (had to also set some of the ones that are present in the Travis build).

The blocker right now is that the following error occurs during compilation:

```
error: proc-macro derive panicked
  --> src/config.rs:30:10
   |
30 | #[derive(Deserialize)]
   |          ^^^^^^^^^^^
   |
   = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `tectonic`.
```

According to rust-lang-nursery/rustfmt#1573, this seems to be an issue with Homebrew's Rust distribution. The problem is that AFAIK, we need to use Homebrew's Rust during the installation of a formula (since it's specified as a build dependency).

**Comment by alexreg** [comment] 2017-06-03 21:06
@iKevinY I recommend making the Homebrew Rust dependency optional. That's the typical way to do it, to allow for it to be run on non-Homebrew Rust.

**Comment by iKevinY** [comment] 2017-06-03 21:16
@alexreg Are there existing formulae that use that approach? I did a brief search of `homebrew-core`, but everything I found had a strict `depends_on "rust" => :build` requirement.

**Comment by alexreg** [comment] 2017-06-03 21:26
@iKevinY Not for Rust, but a similar model for e.g. Mono is used, so I think it's quite acceptable. I've discussed it with the Homebrew maintainer-in-chief before. :)

**Comment by iKevinY** [comment] 2017-06-03 22:29
@alexreg Ah, I see! In that case, I'll see if I can get it working with Rust as an optional dependency.

**Comment by alexreg** [comment] 2017-06-03 23:11
@iKevinY Feel free to run the formula by me before you open a PR over at homebrew-core. I have experience creating and updating many Homebrew formulas before. :)

**Comment by iKevinY** [comment] 2017-06-04 22:31
@alexreg As far as I can tell, formulae that depend on Mono make it an optional dependency because they don't want to install the Homebrew variant if it has already been installed on the system through some other means (ie. Xamarin). However, there's nothing inherently wrong with using Homebrew's version of Mono instead.

With our case, "Homebrew Rust" is broken with respect to compiling Tectonic, so even if we made Rust an optional dependency, the installation would fail _whenever_ someone tried using Homebrew Rust (including, for example, Homebrew's CI). This means that the formula would essentially require Rust to be installed externally via `rustup` before attempting a `brew install`, and this seems to go against Homebrew's usage model.

**Comment by alexreg** [comment] 2017-06-04 23:32
@iKevinY That's correct. So, we want to make it an optional dependency, *and* fix the Homebrew Rust, ideally. Do you know where the Homebrew Rust problem originates?

**Comment by iKevinY** [comment] 2017-06-05 00:11
@alexreg It's something to do with how Homebrew interacts with dynamic libraries:

- Another occurrence of the same compiler error: rust-lang-nursery/rustfmt#1573
- Some discussion about the underlying cause: rust-lang/rust#39870
- Fix that was briefly merged into Homebrew, then reverted: Homebrew/brew#2036

**Comment by alexreg** [comment] 2017-06-05 00:47
Ugh, sounds nasty, @iKevinY. Want to ping that thread on Homebrew, and see what the latest is?

**Comment by ilovezfs** [comment] 2017-06-12 05:55
This should no longer be a problem in Homebrew due to https://github.com/Homebrew/homebrew-core/pull/14490.

**Comment by iKevinY** [comment] 2017-06-12 06:32
@ilovezfs Fantastic, huge thanks to you and @woodruffw for getting that merged in! Hopefully I'll be able to open a PR for the Homebrew formula within the next few days.

**Comment by alexreg** [comment] 2017-06-12 16:04
Great. Let me know if you need help with the Homebrew formula, @iKevinY, as I have extensive experience writing these. :)

**Comment by iKevinY** [comment] 2017-06-13 01:32
@alexreg Any ideas on what to put in the `test` block? In theory, it should be something like processing a minimal document, but that requires downloading a bunch of packages, which isn't ideal.

**Comment by alexreg** [comment] 2017-06-13 02:31
@iKevinY Something that tests the execution of some basic TeX macros and verifies the output would be fine. I agree we want to avoid downloading any packages, but we can still do some basic tests using the built-in macros.

**Comment by iKevinY** [comment] 2017-06-13 04:07
@alexreg @pkgw Is there any way to invoke `tectonic` without it attempting to download packages? Even when running it on an empty file, it appears to initiate some downloads.

**Comment by alexander-bauer** [comment] 2017-06-13 13:45
@iKevinY @alexreg Would it be possible to just invoke the existing test suite, or a subset of it? The only way I know of executing it requires `cargo`, but you might be able to work around that. The `tex-outputs` test suite does what you've described: test output without downloading any packages.

**Comment by ilovezfs** [comment] 2017-06-13 13:50
FWIW downloads in the test block are acceptable. For example, node runs npm install for npm@latest and bignum, and the agda test runs cabal install for text and ieee754.

**Comment by alexreg** [comment] 2017-06-13 22:53
@ilovezfs Are you sure? I think they're considered rather undesirable in any case.

**Comment by alexreg** [comment] 2017-06-13 22:54
@alexander-bauer There's nothing wrong with requiring *cargo* though, since it's bundled with Rust already. But thanks for the info, that may be the way to go. :)

**Comment by iKevinY** [comment] 2017-06-14 05:45
> Would it be possible to just invoke the existing test suite, or a subset of it?

I think the idea of the `test` block is to make sure the program was installed properly, so the test should probably include invoking `tectonic`, rather than just its test suite.

> FWIW downloads in the test block are acceptable.

When I clear Tectonic's cache and try to process an empty file, it takes about 3 minutes to download the packages, which definitely isn't ideal. Also, there have already been instances where people can't access PURL (such as #59), so we wouldn't want that blocking the installation itself.

I'll open a PR with what I currently have written to help facilitate this discussion.

**Comment by pkgw** [comment] 2017-06-14 16:30
Great work, Homebrewers!

I've gotten a bit ambitious and set up a Discourse forum site for Tectonic discussions that don't quite fit within the topical bounds appropriate GitHub issues or StackExchange Q&A's: https://tectonic.newton.cx/ . It would be great if someone make a quick post announcing availability of the Homebrew package once it gets finalized 😄

**Comment by tdehaeze** [comment] 2017-06-20 16:27
Same for Fedora, you get
```
error: failed to run custom build command for `tectonic v0.1.5`
process didn't exit successfully: `/tmp/cargo-install.YPyTKukq0ilx/release/build/tectonic-288ff062025165a8/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"fontconfig harfbuzz harfbuzz-icu icu-uc freetype2 graphite
2 libpng zlib\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package graphite2 was not found in the pkg-config search path.\nPerhaps you should add the directo
ry containing `graphite2.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'graphite2\' found\n" } }', /checkout/src/libcore/result.rs:859
```

You have to install `graphite2-devel` by running `sudo dnf install graphite2-devel`

**Comment by pkgw** [comment] 2017-06-21 12:28
@tdehaeze Hm, I would have thought that `harfbuzz-devel` would have pulled that in automatically since Fedora's `harfbuzz` includes a `graphite2` module. Oh well, whatever. Thanks for the report; the website has been updated.

**Comment by iKevinY** [comment] 2017-06-25 22:57
There's a couple of issues that need to be resolved before getting Tectonic into Homebrew (see Homebrew/homebrew-core#14575). If anyone has ideas on how to fix these, it would be much appreciated! (I've also opened a [forum thread](https://tectonic.newton.cx/t/getting-tectonic-into-homebrew/38) to track this.)

**Closed** 2020-01-07 00:14 UTC
