### ISSUE TITLE
Automatically deploy PKGBUILD to AUR

### ISSUE THREAD

**Issue by alexander-bauer** [tectonic-typesetting/tectonic#54] opened 2017-06-01 21:01 UTC
The AUR accepts package updates via Git, so updating an AUR package is as simple as pushing a git repository to their server. This repository must have the PKGBUILD at its root, however. One way I think we can accomplish this is to extract the `dist/arch/` directory as a subtree on-the-fly, and push that to the AUR as one step in a continuous deployment pipeline.  If the subtree is extracted in the same way every time, it will keep the same history, with just the commits relevant to that directory, regardless of when or where it is generated.

Doing this would mean collaborating with @jtojnar, who owns the package on the AUR.

**Comment by jtojnar** [comment] 2017-06-01 21:30
I think the most reasonable would be creating a new AUR account and adding it as co-maintainer. Then adding the following script into [deploy section](https://docs.travis-ci.com/user/deployment/script/) of `.travis.yml`.

```shell
git clone ssh://aur@aur.archlinux.org/tectonic.git staging/arch
cp dist/arch/PKGBUILD staging/arch
cd staging/arch
mksrcinfo
git add PKGBUILD .SRCINFO
git commit -m "Release $TRAVIS_TAG"
git push origin master
```

For generating [`.SRCINFO`](https://wiki.archlinux.org/index.php/.SRCINFO) we can either use [`makepkg`](https://www.archlinux.org/packages/?name=pacman) or probably easier [`pkgbuild-introspection`](https://www.archlinux.org/packages/?name=pkgbuild-introspection) (only depends on bash).

We would also need to add a private key for deploying. This looks like another area where Travis is not optimal but we could always try to store it in an environment variable and then save it to a proper file in the script.

**Comment by pkgw** [comment] 2017-06-02 13:23
I will leave it to you two (and other Arch Linux users) to think about how you'd like to do this.

Am I understanding correctly that in this model, every push to `master` would result in an update of the AUR git repo and a new version appearing on the AUR? Is that standard practice? If it is also common to only push updates for new tagged upstream releases, I might prefer that model — life as a maintainer is a bit easier if your users aren't running ever-changing unreleased versions of the package.

**Comment by jtojnar** [comment] 2017-06-02 15:52
In AUR, there are two kinds of packages: Normal packages that get updated when a new version is tagged, and VCS packages that always fetch the current `HEAD` and need to be updated only when dependencies change. The `tectonic` package is the former one, since it lacks `-git` suffix.

Travis allows you to mark deploy scenarios to run only when a tag is added, see [conditional releases](https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on).

**Comment by alexander-bauer** [comment] 2017-06-02 20:31
@jtojnar It looks like the way to accomplish deployment with Travis will be to store the ssh key in the repository, but keep it encrypted with Travis's [file encrypting capabilities](https://docs.travis-ci.com/user/encrypting-files/). We'll have to collaborate with @pkgw to generate a "deploy" keypair, and to store the encrypted one in the repository with the Travis key. After that, we can create an AUR user as a co-maintainer and install the deploy public key.

**Comment by pkgw** [comment] 2017-06-02 22:18
OK, I am happy to generate a keypair and get an encrypted private key into `.travis.yml` if you can outline any unusual settings for the SSH keys and what bits need to go into the Travis file.

**Comment by alexander-bauer** [comment] 2017-06-03 15:26
@pkgw If you are willing, I think these are the steps that you'll need to do, as someone with Travis access:

1. Generate a standard ssh keypair without a password using `ssh-keygen` and put the results where in the repository (I suggest `dist/deploy_key`, but you may want a separate directory)
1. Check in the public key (`dist/deploy_key.pub`), but *not* the private one (`dist/deploy_key`)
1. Install and log into the Travis CLI client `gem install travis && travis login`
1. Encrypt the secret key, adding the associated command to the Travis file: `travis encrypt-file dist/deploy_key --add`
1. Add the resulting `dist/deploy_key.enc` and changes to `.travis.yml` to the repository

Afterward, if you're so inclined, you can remove or shred the unencrypted private key. Once this public key is available, @jtojnar and I can collaborate to figure out the rest.

**Comment by pkgw** [comment] 2017-06-04 12:42
OK. CC #65. I *think* that I had to monkey with the file path in the `.travis.yml` (its suggested change named the file as just `deploy_key` not `dist/deploy_key`) but wanted to put it through a CI run to double-check that.

**Comment by alexander-bauer** [comment] 2017-06-04 17:10
With the key now extant (thanks @pkgw!), I think the next step is to create an automated `tectonic-deploy` user on the AUR with that public key installed. It would be much nicer to add the key directly to the AUR repository as a deploy key, like GitHub does, but the AUR doesn't have that feature.

I've gone ahead and created this user (`tectonic-deploy`), and think the following steps are next:
1. Change the email address to one associated with the Tectonic project, if one exists. Otherwise, I can keep hold of it.
1. Add it as a co-maintainer on the AUR project. This will require @jtojnar's doing.
1. Add the `deploy` step of the Travis build.

**Comment by jtojnar** [comment] 2017-06-04 19:16
I added the user as co-maintainer, will try to create the `deploy` script later.

**Comment by pkgw** [comment] 2017-06-05 00:52
@alexander-bauer For the time being, I guess you can/should keep the account associated with your email address. If more of these accounts need to be created I guess I will make a GMail account for the project leadership — this is also something that comes up in the [Code of Conduct](https://github.com/tectonic-typesetting/tectonic/blob/master/CODE_OF_CONDUCT.md#enforcement).

**Comment by pkgw** [comment] 2017-07-08 15:09
It seems as if the autodeploy didn't quite work: see [the Travis build log](https://travis-ci.org/tectonic-typesetting/tectonic/jobs/251498381).

**Comment by alexander-bauer** [comment] 2017-07-08 15:20
I'm on my phone at the moment, but from what I can see it looks like
there's an erroneous `git commit` when there isn't a branch checked out.
Should be an easy fix?

**Comment by jtojnar** [comment] 2017-07-08 21:06
I do not see why a branch would not be checked out. Cloning it locally chooses master.

On a side note, I switched my Arch machine to NixOS so AUR packaging is no longer a priority for me. I can transfer the ownership to you, if you wish.

**Comment by pkgw** [comment] 2017-07-09 14:01
I think I might want to tag another release shortly to update the Documentation link on crates.io. So if anyone has a chance to try to solve this in the near future, there can be a chance to test the fix :-)

**Comment by alexander-bauer** [comment] 2017-07-09 14:02
I'm happy to take ownership of the aur package; I'll hopefully have some
time to resolve this tonight or tomorrow.

**Comment by jtojnar** [comment] 2017-07-11 14:39
@alexander-bauer I transferred the package to you.

**Comment by pkgw** [comment] 2018-09-29 01:11
Hello, folks that have previously been interested in packaging Tectonic on Arch Linux! It's been a while — apologies for not being super attentive to this aspect of things.

I put out a 0.1.10 release today, and I decided to spend a bit of time trying to figure out the status of automatic deployment to the AUR. There were definitely a few problems. I've fixed some of the more superficial ones, but it's still not quite working.

[Here's the latest build log](https://travis-ci.org/tectonic-typesetting/tectonic/jobs/434859760#L1548). As far as I can tell, the SSH key that we're trying to use to deploy just isn't working. Would that have changed in the past year or so?

**Comment by pkgw** [comment] 2018-09-30 19:16
@jtojnar Looking at [the AUR page](https://aur.archlinux.org/packages/tectonic/), perhaps the problem is that the `tectonic-deploy` user is not a co-maintainer? Are you able to alter that?

I realized that the past few releases wouldn't have worked anyway because I wasn't updating the `PKGBUILD` file — I didn't realize it needed maintenance. I will try to keep it updated going forward.

**Comment by jtojnar** [comment] 2018-09-30 20:30
@polyzen I do not use Arch any more, so I transferred it back to you.

**Comment by pkgw** [comment] 2018-09-30 21:17
It worked! Thanks all for assisting.

@polyzen It appears the `pkgbuild-introspection` has been removed — see the comment at the bottom of [its package page](https://aur.archlinux.org/packages/pkgbuild-introspection/). That's why I switched away from it.

**Closed by pkgw** 2018-09-30 21:17 UTC
