### ISSUE TITLE
error: the external tool exited with an error code

### ISSUE THREAD

**Issue by S3bTheGuy** [tectonic-typesetting/tectonic#1000] opened 2023-02-07 11:59 UTC
it seems tectonic has seemingly stopped working after having updated biber/biblatex 
the error looks as follows: 
```
===============================================================================
INFO - This is Biber 2.18
INFO - Logfile is 'main.blg'
INFO - Reading 'main.bcf'
ERROR - Error: Found biblatex control file version 3.8, expected version 3.9.
This means that your biber (2.18) and biblatex (3.17) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
===============================================================================
```
I am using biblatex version 3.18b and my main.bcf in my /out dir is `controlfile version="3.9" bltxversion="3.18b"` 
Pdflatex and biber on it's own have no trouble running.

**Comment by pkgw** [comment] 2023-02-11 15:37
This problem is basically #893, so I'm going to close this issue as a duplicate of it — you can subscribe to that issue and review the discussion there to see the current situation. The short explanation is that the biber/biblatex system relies on pretty tight coupling between the TeX files and the external program, and Tectonic only controls the TeX half of that pairing, so things can get out of sync in this way. Unfortunately we don't have a great resolution to this problem, although depending on your circumstances, there might be some fairly easy workarounds to use.

**Closed** 2023-02-11 15:37 UTC
