### ISSUE TITLE
Unable to Compile on Debian Stable: "failed to parse lock file"

### ISSUE THREAD

**Issue by ndegruchy** [tectonic-typesetting/tectonic#644] opened 2020-09-22 14:56 UTC
Following the directions from [the documentation][1], I get to the point where I run

`$ cargo install tectonic`

After a short while (where cargo updates it's list from crates.io). I get the following error:

```
❯ cargo install tectonic
    Updating crates.io index
  Installing tectonic v0.1.15
error: failed to compile `tectonic v0.1.15`, intermediate artifacts can be found at `/tmp/cargo-installBlDURR`

Caused by:
  failed to parse lock file at: /home/nathan/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/tectonic-0.1.15/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```
The temp directory mentioned contains no build artifacts, and I don't see anything *immediately* wrong with the lock file, but it's quite long.

Cargo Version:

```
❯ cargo --version
cargo 1.34.0
```

Debian version:

```
❯ uname -a
Linux ndegruchy-lt 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

What else can I provide to help with this issue?

Thanks!

[1]: https://tectonic-typesetting.github.io/en-US/install.html#debian-and-ubuntu-linux

**Comment by ndegruchy** [comment] 2020-09-22 15:02
I did run the contents of the lock file through the TOML linter and, as I would imagine, it's a valid TOML file, so I don't know what Cargo's problem is...


![Screenshot_2020-09-22 TOML Lint - The TOML Validator](https://user-images.githubusercontent.com/52262673/93900072-fb686800-fcc2-11ea-8f02-1435a6c291f4.png)

**Comment by pkgw** [comment] 2020-10-11 15:14
Sorry for taking a little while to reply to this.

Based on this Reddit thread:

https://www.reddit.com/r/rust/comments/9sdm4a/failed_to_parse_a_lock_file_cargolock/

Maybe the issue is that your version of Rust/Cargo are too old? If you're using Debian stable, it's probably on the relatively old side.

**Comment by pkgw** [comment] 2020-11-14 18:58
I'm going to close this issue because I think that the cause has been identified and there's no follow-up to the contrary. Please reopen or re-file if there's more to investigate.

**Closed by pkgw** 2020-11-14 18:58 UTC
