### ISSUE TITLE
White space in argument

### ISSUE THREAD

**Issue by ncihnegn** [tectonic-typesetting/tectonic#1105] opened 2023-10-14 21:13 UTC
Running tectonic 0.14.1 on https://github.com/sneakers-the-rat/dissertation gives
```
error: something bad happened inside BibTeX; its output follows:

===============================================================================
White space in argument---line 2393 of file jls_dissertation_institutional.aux
 : \citation{goodmanEndingSupportLegacy2022
 :                                          }
I'm skipping whatever remains of this command
field_info index is out of range---this can't happen
*Please notify the Tectonic maintainer*
Aborted at line 39 of file bibliographies/dissertation_combined.bib
(That was a fatal error)
```

**Comment by CraftSpider** [comment] 2023-10-15 02:09
Almost definitely a result of my port, I'll look into it.

**Comment by Neved4** [comment] 2023-10-23 11:54
It's a syntax error in line `5196`, the `\citep` command expects a single ending `}` but it's given two braces instead.

See: [infrastructure_dissertation.tex#L5196](https://github.com/sneakers-the-rat/infrastructure/blob/1a6ead2cb17216f9bc0e1137a0346633d006cf64/tex/infrastructure_dissertation.tex#L5196) and [infrastructure_dissertation.tex#L5196](https://github.com/sneakers-the-rat/infrastructure/blob/1a6ead2cb17216f9bc0e1137a0346633d006cf64/tex/infrastructure_dissertation_institutional.tex#L5196).

**Comment by vlasakm** [comment] 2023-10-23 22:41
> It's a syntax error in line `5196`, the `\citep` command expects a single ending `}` but it's given two braces instead.
> 
> See: [infrastructure_dissertation.tex#L5196](https://github.com/sneakers-the-rat/infrastructure/blob/1a6ead2cb17216f9bc0e1137a0346633d006cf64/tex/infrastructure_dissertation.tex#L5196) and [infrastructure_dissertation.tex#L5196](https://github.com/sneakers-the-rat/infrastructure/blob/1a6ead2cb17216f9bc0e1137a0346633d006cf64/tex/infrastructure_dissertation_institutional.tex#L5196).

I don't think that's the issue -- the second `}` pairs to the preceding `\sidenote{`.

**Comment by Neved4** [comment] 2023-10-24 00:15
@vlasakm You're right, after more careful inspection that's not what the cause is.

**Comment by CraftSpider** [comment] 2023-10-24 19:34
Sorry for the delay - I'm busy currently, but I'll be trying to get to this soon. I suspect the issue is with my bibtex port (converting the legacy C code to Rust), and in that case it's likely due to an off-by-one error or a missed call in my changes that the tectonic-on-arxiv tests (which run tectonic, including the bundled bibtex, against a lot of arxiv documents) didn't cover. If that's the case, I'll make sure to add a regression test so it doesn't happen in the future.

**Comment by Neved4** [comment] 2023-10-24 20:54
Regarding the `.bib` files and your port, they compile using `tectonic` as well as LuaLaTeX / XeTeX, both producing `1080` references:

#### MWE `test.tex`

```latex
\documentclass{article}
  \usepackage{amsmath, amsfonts}
  \usepackage[style=numeric,citestyle=numeric,
    backref=true,sorting=none]{biblatex}
    \addbibresource{autopilot.bib}
    \addbibresource{infrastructure.bib}
    \addbibresource{speech_modeling.bib}
    \addbibresource{speech.bib}
  \usepackage{totcount}
    \newtotcounter{citenum}
    \AtEveryBibitem{\stepcounter{citenum}}

\begin{document}
  \nocite{*}
  \printbibliography[title=\bibname{} (\the\totvalue{citenum})]
\end{document}
```

#### Compile with
```sh
path='/usr/local/texlive/2023basic/texmf-dist/tex/latex/biblatex'

tectonic -p test.tex -Z search-path="$path"
```

###### * The search path could vary on your system, adjust it accordingly.

**Comment by CraftSpider** [comment] 2023-12-02 00:35
I think I found the root cause and will be opening a PR shortly - the actual issue was small, despite taking me several hours to track down. A test will be included to prevent regressions.

**Closed** 2023-12-02 16:02 UTC
